In [2]:
import numpy as np

In [3]:
#Data Creation

students=np.array(["Pradeep","Goutham","Shaheen","Deepak","Hruthik"])
subjects=np.array(["Social","Maths","Science","Physics"])

marks=np.array([
    [78,96,75,84],
    [74,85,76,96],
    [74,95,78,69],
    [73,74,89,94],
    [74,84,75,95]])

print(students)
print(subjects)
print(marks)

['Pradeep' 'Goutham' 'Shaheen' 'Deepak' 'Hruthik']
['Social' 'Maths' 'Science' 'Physics']
[[78 96 75 84]
 [74 85 76 96]
 [74 95 78 69]
 [73 74 89 94]
 [74 84 75 95]]


In [4]:
#Data Exploration

print(marks.ndim)
print(marks.shape)
print(marks.size)
print(marks.dtype)

2
(5, 4)
20
int64


In [5]:
#Data Transformation

marks_t=marks.T
print(marks_t)

flatten=marks.flatten()
print(flatten)

[[78 74 74 73 74]
 [96 85 95 74 84]
 [75 76 78 89 75]
 [84 96 69 94 95]]
[78 96 75 84 74 85 76 96 74 95 78 69 73 74 89 94 74 84 75 95]


In [6]:
#Data Combination

new_student_marks=np.array([[78,96,74,85]])
marks=np.vstack([marks, new_student_marks])
students=np.append(students, "Sidharth")

print(students)
print(marks)

new_subject_marks=np.array([[96], [75], [48] ,[78] , [45], [89]])
marks=np.hstack([marks, new_subject_marks])
subjects=np.append(subjects, "Computer")

print(marks)
print(subjects)

['Pradeep' 'Goutham' 'Shaheen' 'Deepak' 'Hruthik' 'Sidharth']
[[78 96 75 84]
 [74 85 76 96]
 [74 95 78 69]
 [73 74 89 94]
 [74 84 75 95]
 [78 96 74 85]]
[[78 96 75 84 96]
 [74 85 76 96 75]
 [74 95 78 69 48]
 [73 74 89 94 78]
 [74 84 75 95 45]
 [78 96 74 85 89]]
['Social' 'Maths' 'Science' 'Physics' 'Computer']


In [7]:
#Data Modification

print(marks[1,2])
marks[1,2]=90
print(marks)

marks=np.delete(marks,4,axis=0)
students=np.delete(students, 4)
print(marks)
print(students)

76
[[78 96 75 84 96]
 [74 85 90 96 75]
 [74 95 78 69 48]
 [73 74 89 94 78]
 [74 84 75 95 45]
 [78 96 74 85 89]]
[[78 96 75 84 96]
 [74 85 90 96 75]
 [74 95 78 69 48]
 [73 74 89 94 78]
 [78 96 74 85 89]]
['Pradeep' 'Goutham' 'Shaheen' 'Deepak' 'Sidharth']


In [8]:
#Data type handling

marks_float=marks.astype(float)
print(marks_float)

marks_str=marks.astype(str)
print(marks_str)

[[78. 96. 75. 84. 96.]
 [74. 85. 90. 96. 75.]
 [74. 95. 78. 69. 48.]
 [73. 74. 89. 94. 78.]
 [78. 96. 74. 85. 89.]]
[['78' '96' '75' '84' '96']
 ['74' '85' '90' '96' '75']
 ['74' '95' '78' '69' '48']
 ['73' '74' '89' '94' '78']
 ['78' '96' '74' '85' '89']]


In [9]:
#Copy vs view

copy_marks=marks.copy()
view_marks=marks.view()

view_marks[0,0]=100

print(copy_marks) #unaffected
print(view_marks) #affected

[[78 96 75 84 96]
 [74 85 90 96 75]
 [74 95 78 69 48]
 [73 74 89 94 78]
 [78 96 74 85 89]]
[[100  96  75  84  96]
 [ 74  85  90  96  75]
 [ 74  95  78  69  48]
 [ 73  74  89  94  78]
 [ 78  96  74  85  89]]


In [10]:
#Data analysis examples

print(np.mean(marks, axis=0))
print(np.mean(marks, axis=1))
print(np.max(marks))
print(np.unique(marks))

[79.8 89.2 81.2 85.6 77.2]
[90.2 84.  72.8 81.6 84.4]
100
[ 48  69  73  74  75  78  84  85  89  90  94  95  96 100]
